### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'range')

### ISSUE THREAD

**Issue by hanayashiki** [fostimus/eslint-plugin-svg-jsx#9]
Hi, I got the following exception when linting my react/typescript project:

```tsx
pnpm eslint --ext .ts,.tsx .

Oops! Something went wrong! :(

ESLint: 8.56.0

TypeError: Cannot read properties of undefined (reading 'range')
Occurred while linting /Users/chenyuwang/pawpawmall/packages/store/src/routes/_root.my-page.mail-settings.tsx:167
Rule: "svg-jsx/camel-case-dash"
    at Object.replaceText (/Users/chenyuwang/pawpawmall/node_modules/.pnpm/eslint@8.56.0/node_modules/eslint/lib/linter/rule-fixer.js:95:50)
    at Object.fix (/Users/chenyuwang/pawpawmall/node_modules/.pnpm/eslint-plugin-svg-jsx@1.2.2/node_modules/eslint-plugin-svg-jsx/rules/camel-case-dash.js:61:29)
    at normalizeFixes (/Users/chenyuwang/pawpawmall/node_modules/.pnpm/eslint@8.56.0/node_modules/eslint/lib/linter/report-translator.js:194:28)
    at /Users/chenyuwang/pawpawmall/node_modules/.pnpm/eslint@8.56.0/node_modules/eslint/lib/linter/report-translator.js:365:49
    at Object.report (/Users/chenyuwang/pawpawmall/node_modules/.pnpm/eslint@8.56.0/node_modules/eslint/lib/linter/linter.js:1047:41)
    at validateAndFixProp (/Users/chenyuwang/pawpawmall/node_modules/.pnpm/eslint-plugin-svg-jsx@1.2.2/node_modules/eslint-plugin-svg-jsx/rules/camel-case-dash.js:51:23)
    at /Users/chenyuwang/pawpawmall/node_modules/.pnpm/eslint-plugin-svg-jsx@1.2.2/node_modules/eslint-plugin-svg-jsx/rules/camel-case-dash.js:79:13
    at Array.forEach (<anonymous>)
    at handleSpreadOperator (/Users/chenyuwang/pawpawmall/node_modules/.pnpm/eslint-plugin-svg-jsx@1.2.2/node_modules/eslint-plugin-svg-jsx/rules/camel-case-dash.js:74:17)
    at /Users/chenyuwang/pawpawmall/node_modules/.pnpm/eslint-plugin-svg-jsx@1.2.2/node_modules/eslint-plugin-svg-jsx/rules/camel-case-dash.js:94:15
```

The code to lint is:

```tsx
<MyPageForm
  {...emailForm.bindForm({
    async onSubmit(body) {},
  })}
>
  {...}
</MyPageForm>
```

Although I'm not quite understanding this library, the problem seems to be that `nodeToFix` is possibly undefined.

```js
        function handleSpreadOperator(attr, charDelimtiter) {
          const props = getPropsFromObjectString(getPropIdentifier(attr, context))
          props.forEach((prop) => {
            const nodeToFix = attr?.argument?.properties?.find((node) => {
              return node?.key?.value === prop
            })?.key

            validateAndFixProp(prop, nodeToFix, charDelimtiter)
          })
        }
```

**Comment by fostimus** [comment]
I wasn't able to reproduce this, this is the sample code I used:

```js
const testArray = {
    thing: 'thing',
  }

  return (
    <EmbedForm
      {...testArray.bindForm({
         async onSubmit (body) {},
      })}
    >
      tjing
    </EmbedForm>
  )
```

Can you send me the JS/TSX file you're using this with? It looks like you're using TypeScript, which the characters might be interpreted slightly different. I've only tested this with JavaScript

**Comment by hanayashiki** [comment]
> I wasn't able to reproduce this, this is the sample code I used:
> 
> ```js
> const testArray = {
>     thing: 'thing',
>   }
> 
>   return (
>     <EmbedForm
>       {...testArray.bindForm({
>          async onSubmit (body) {},
>       })}
>     >
>       tjing
>     </EmbedForm>
>   )
> ```
> 
> Can you send me the JS/TSX file you're using this with? It looks like you're using TypeScript, which the characters might be interpreted slightly different. I've only tested this with JavaScript

Thank you for taking a look!

I have a reproduction with typescript here: https://github.com/hanayashiki/eslint-plugin-svg-jsx-issue-9-repro
